main: de.raidcraft.rceconomy.RCEconomyPlugin
name: RCEconomy
version: ${project.version}#${build.number}
description: Provides money transfer.
author: Strasse36
website: http://www.raid-craft.de
depend: [RaidCraft-API]